# Generated by Django 6.1.1 on 2026-09-06 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_remove_restaurant_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Restaurant Owner'), ('STAFF', 'Restaurant Staff')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
            ],
            options={
                'verbose_name': 'Restaurant Owner',
                'verbose_name_plural': 'Restaurant Owners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.restaurantmembership',),
        ),
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
            ],
            options={
                'verbose_name': 'Restaurant Staff',
                'verbose_name_plural': 'Restaurant Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.restaurantmembership',),
        ),
        migrations.AddConstraint(
            model_name='restaurantmembership',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_user_restaurant_membership'),
        ),
    ]
