# Generated by Django 6.1.1 on 2026-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_cover_image_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_layout',
            field=models.CharField(choices=[('classic', 'Classic'), ('cards', 'Cards'), ('showcase', 'Showcase')], default='cards', max_length=20),
        ),
    ]
