# Generated by Django 6.1.1 on 2026-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_menu_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
    ]
