# Generated by Django 6.1.1 on 2026-09-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='speciality_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='speciality_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
