# Generated by Django 6.1.1 on 2026-09-10 10:59

import django.db.models.deletion
import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurantgallery_signaturedish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('video_1', models.FileField(blank=True, null=True, upload_to=restaurants.models.review_video_upload_path)),
                ('video_2', models.FileField(blank=True, null=True, upload_to=restaurants.models.review_video_upload_path)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_section', to='restaurants.restaurant')),
            ],
        ),
    ]
