# Generated by Django 6.1.1 on 2026-09-10 18:00

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_reviewsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsection',
            name='ideo_3',
            field=models.FileField(blank=True, null=True, upload_to=restaurants.models.review_video_upload_path),
        ),
        migrations.AddField(
            model_name='reviewsection',
            name='video_4',
            field=models.FileField(blank=True, null=True, upload_to=restaurants.models.review_video_upload_path),
        ),
    ]
