# Generated by Django 6.1.1 on 2026-09-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_reviewsection_ideo_3_reviewsection_video_4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsection',
            old_name='ideo_3',
            new_name='video_3',
        ),
    ]
