# Generated by Django 6.1.1 on 2026-09-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_rename_ideo_3_reviewsection_video_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='google_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
    ]
