# Generated by Django 6.1.1 on 2026-09-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurant_facebook_url_restaurant_google_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('dark', 'Dark'), ('elegant', 'Elegant'), ('fresh', 'Fresh'), ('ocean', 'Ocean'), ('minimal', 'Minimal')], default='classic', max_length=20),
        ),
    ]
