# Generated by Django 6.1.1 on 2026-09-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menuitemvariant_price_max_menuitemvariant_price_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemvariant',
            name='price_range',
            field=models.BooleanField(default=False, help_text='Enable this if the price varies by fish size/weight.'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='name',
            field=models.CharField(help_text='Example: Squid, Prawns, King Fish, Regular, Large', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the fixed price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price.', max_digits=10, null=True),
        ),
    ]
