# Generated by Django 6.1.1 on 2026-09-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menuitemvariant_price_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the fixed price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the maximum price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the minimum price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_range',
            field=models.BooleanField(default=False, help_text='Enable this if the price varies by size or weight.'),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this variant.', null=True, upload_to='menus/variants/'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the maximum price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the minimum price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='price_range',
            field=models.BooleanField(default=False, help_text='Enable this if the variant price varies by size or weight.'),
        ),
    ]
