# Generated by Django 6.1.1 on 2026-09-07 17:57

import menus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menuitem_price_menuitem_price_max_menuitem_price_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=menus.models.menu_item_image_upload_path),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this variant.', null=True, upload_to=menus.models.menu_variant_image_upload_path),
        ),
    ]
